package com.utstar.adhandler.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table adplace
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Adplace implements Serializable {
    /**
     * Database Column Remarks:
     *   primary key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.adplaceid
     *
     * @mbg.generated
     */
    private Integer adplaceid;

    /**
     * Database Column Remarks:
     *   refer to domain.domainid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.domainid
     *
     * @mbg.generated
     */
    private Integer domainid;

    /**
     * Database Column Remarks:
     *   位置ID，和广告终端对应
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.posid
     *
     * @mbg.generated
     */
    private String posid;

    /**
     * Database Column Remarks:
     *   广告位名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   广告位类型 1：视频 2：图片 3：文本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   尺寸,格式如400*300,单位px
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.sizes
     *
     * @mbg.generated
     */
    private String sizes;

    /**
     * Database Column Remarks:
     *   广告播放个数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.playsize
     *
     * @mbg.generated
     */
    private Integer playsize;

    /**
     * Database Column Remarks:
     *   预估平均日流量，单位：次
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.pretimesperday
     *
     * @mbg.generated
     */
    private Integer pretimesperday;

    /**
     * Database Column Remarks:
     *   刷新周期，单位：分钟
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.refreshperiod
     *
     * @mbg.generated
     */
    private Integer refreshperiod;

    /**
     * Database Column Remarks:
     *   广告位价格，单位：元
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     * Database Column Remarks:
     *   可用状态 0：不可用 1：可用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.usableflag
     *
     * @mbg.generated
     */
    private String usableflag;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.createdate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.staffid
     *
     * @mbg.generated
     */
    private Integer staffid;

    /**
     * Database Column Remarks:
     *   默认广告id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.defaultadid
     *
     * @mbg.generated
     */
    private Integer defaultadid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     * Database Column Remarks:
     *   左上坐标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.top
     *
     * @mbg.generated
     */
    private String top;

    /**
     * Database Column Remarks:
     *   左下坐标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.left
     *
     * @mbg.generated
     */
    private String left;

    /**
     * Database Column Remarks:
     *   宽度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.width
     *
     * @mbg.generated
     */
    private String width;

    /**
     * Database Column Remarks:
     *   高度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.height
     *
     * @mbg.generated
     */
    private String height;

    /**
     * Database Column Remarks:
     *   广告显示方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.showtype
     *
     * @mbg.generated
     */
    private String showtype;

    /**
     * Database Column Remarks:
     *   EPG模板代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.epgtempalatecode
     *
     * @mbg.generated
     */
    private String epgtempalatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adplace
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.adplaceid
     *
     * @return the value of adplace.adplaceid
     *
     * @mbg.generated
     */
    public Integer getAdplaceid() {
        return adplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.adplaceid
     *
     * @param adplaceid the value for adplace.adplaceid
     *
     * @mbg.generated
     */
    public void setAdplaceid(Integer adplaceid) {
        this.adplaceid = adplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.domainid
     *
     * @return the value of adplace.domainid
     *
     * @mbg.generated
     */
    public Integer getDomainid() {
        return domainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.domainid
     *
     * @param domainid the value for adplace.domainid
     *
     * @mbg.generated
     */
    public void setDomainid(Integer domainid) {
        this.domainid = domainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.posid
     *
     * @return the value of adplace.posid
     *
     * @mbg.generated
     */
    public String getPosid() {
        return posid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.posid
     *
     * @param posid the value for adplace.posid
     *
     * @mbg.generated
     */
    public void setPosid(String posid) {
        this.posid = posid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.name
     *
     * @return the value of adplace.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.name
     *
     * @param name the value for adplace.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.code
     *
     * @return the value of adplace.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.code
     *
     * @param code the value for adplace.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.type
     *
     * @return the value of adplace.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.type
     *
     * @param type the value for adplace.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.sizes
     *
     * @return the value of adplace.sizes
     *
     * @mbg.generated
     */
    public String getSizes() {
        return sizes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.sizes
     *
     * @param sizes the value for adplace.sizes
     *
     * @mbg.generated
     */
    public void setSizes(String sizes) {
        this.sizes = sizes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.playsize
     *
     * @return the value of adplace.playsize
     *
     * @mbg.generated
     */
    public Integer getPlaysize() {
        return playsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.playsize
     *
     * @param playsize the value for adplace.playsize
     *
     * @mbg.generated
     */
    public void setPlaysize(Integer playsize) {
        this.playsize = playsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.pretimesperday
     *
     * @return the value of adplace.pretimesperday
     *
     * @mbg.generated
     */
    public Integer getPretimesperday() {
        return pretimesperday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.pretimesperday
     *
     * @param pretimesperday the value for adplace.pretimesperday
     *
     * @mbg.generated
     */
    public void setPretimesperday(Integer pretimesperday) {
        this.pretimesperday = pretimesperday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.refreshperiod
     *
     * @return the value of adplace.refreshperiod
     *
     * @mbg.generated
     */
    public Integer getRefreshperiod() {
        return refreshperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.refreshperiod
     *
     * @param refreshperiod the value for adplace.refreshperiod
     *
     * @mbg.generated
     */
    public void setRefreshperiod(Integer refreshperiod) {
        this.refreshperiod = refreshperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.price
     *
     * @return the value of adplace.price
     *
     * @mbg.generated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.price
     *
     * @param price the value for adplace.price
     *
     * @mbg.generated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.usableflag
     *
     * @return the value of adplace.usableflag
     *
     * @mbg.generated
     */
    public String getUsableflag() {
        return usableflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.usableflag
     *
     * @param usableflag the value for adplace.usableflag
     *
     * @mbg.generated
     */
    public void setUsableflag(String usableflag) {
        this.usableflag = usableflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.createdate
     *
     * @return the value of adplace.createdate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.createdate
     *
     * @param createdate the value for adplace.createdate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.staffid
     *
     * @return the value of adplace.staffid
     *
     * @mbg.generated
     */
    public Integer getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.staffid
     *
     * @param staffid the value for adplace.staffid
     *
     * @mbg.generated
     */
    public void setStaffid(Integer staffid) {
        this.staffid = staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.defaultadid
     *
     * @return the value of adplace.defaultadid
     *
     * @mbg.generated
     */
    public Integer getDefaultadid() {
        return defaultadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.defaultadid
     *
     * @param defaultadid the value for adplace.defaultadid
     *
     * @mbg.generated
     */
    public void setDefaultadid(Integer defaultadid) {
        this.defaultadid = defaultadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.duration
     *
     * @return the value of adplace.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.duration
     *
     * @param duration the value for adplace.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.top
     *
     * @return the value of adplace.top
     *
     * @mbg.generated
     */
    public String getTop() {
        return top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.top
     *
     * @param top the value for adplace.top
     *
     * @mbg.generated
     */
    public void setTop(String top) {
        this.top = top;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.left
     *
     * @return the value of adplace.left
     *
     * @mbg.generated
     */
    public String getLeft() {
        return left;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.left
     *
     * @param left the value for adplace.left
     *
     * @mbg.generated
     */
    public void setLeft(String left) {
        this.left = left;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.width
     *
     * @return the value of adplace.width
     *
     * @mbg.generated
     */
    public String getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.width
     *
     * @param width the value for adplace.width
     *
     * @mbg.generated
     */
    public void setWidth(String width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.height
     *
     * @return the value of adplace.height
     *
     * @mbg.generated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.height
     *
     * @param height the value for adplace.height
     *
     * @mbg.generated
     */
    public void setHeight(String height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.showtype
     *
     * @return the value of adplace.showtype
     *
     * @mbg.generated
     */
    public String getShowtype() {
        return showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.showtype
     *
     * @param showtype the value for adplace.showtype
     *
     * @mbg.generated
     */
    public void setShowtype(String showtype) {
        this.showtype = showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adplace.epgtempalatecode
     *
     * @return the value of adplace.epgtempalatecode
     *
     * @mbg.generated
     */
    public String getEpgtempalatecode() {
        return epgtempalatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adplace.epgtempalatecode
     *
     * @param epgtempalatecode the value for adplace.epgtempalatecode
     *
     * @mbg.generated
     */
    public void setEpgtempalatecode(String epgtempalatecode) {
        this.epgtempalatecode = epgtempalatecode;
    }
}