package com.utstar.adhandler.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdplaceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adplace
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adplace
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table adplace
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public AdplaceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adplace
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdplaceidIsNull() {
            addCriterion("adplaceid is null");
            return (Criteria) this;
        }

        public Criteria andAdplaceidIsNotNull() {
            addCriterion("adplaceid is not null");
            return (Criteria) this;
        }

        public Criteria andAdplaceidEqualTo(Integer value) {
            addCriterion("adplaceid =", value, "adplaceid");
            return (Criteria) this;
        }

        public Criteria andAdplaceidNotEqualTo(Integer value) {
            addCriterion("adplaceid <>", value, "adplaceid");
            return (Criteria) this;
        }

        public Criteria andAdplaceidGreaterThan(Integer value) {
            addCriterion("adplaceid >", value, "adplaceid");
            return (Criteria) this;
        }

        public Criteria andAdplaceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("adplaceid >=", value, "adplaceid");
            return (Criteria) this;
        }

        public Criteria andAdplaceidLessThan(Integer value) {
            addCriterion("adplaceid <", value, "adplaceid");
            return (Criteria) this;
        }

        public Criteria andAdplaceidLessThanOrEqualTo(Integer value) {
            addCriterion("adplaceid <=", value, "adplaceid");
            return (Criteria) this;
        }

        public Criteria andAdplaceidIn(List<Integer> values) {
            addCriterion("adplaceid in", values, "adplaceid");
            return (Criteria) this;
        }

        public Criteria andAdplaceidNotIn(List<Integer> values) {
            addCriterion("adplaceid not in", values, "adplaceid");
            return (Criteria) this;
        }

        public Criteria andAdplaceidBetween(Integer value1, Integer value2) {
            addCriterion("adplaceid between", value1, value2, "adplaceid");
            return (Criteria) this;
        }

        public Criteria andAdplaceidNotBetween(Integer value1, Integer value2) {
            addCriterion("adplaceid not between", value1, value2, "adplaceid");
            return (Criteria) this;
        }

        public Criteria andDomainidIsNull() {
            addCriterion("domainid is null");
            return (Criteria) this;
        }

        public Criteria andDomainidIsNotNull() {
            addCriterion("domainid is not null");
            return (Criteria) this;
        }

        public Criteria andDomainidEqualTo(Integer value) {
            addCriterion("domainid =", value, "domainid");
            return (Criteria) this;
        }

        public Criteria andDomainidNotEqualTo(Integer value) {
            addCriterion("domainid <>", value, "domainid");
            return (Criteria) this;
        }

        public Criteria andDomainidGreaterThan(Integer value) {
            addCriterion("domainid >", value, "domainid");
            return (Criteria) this;
        }

        public Criteria andDomainidGreaterThanOrEqualTo(Integer value) {
            addCriterion("domainid >=", value, "domainid");
            return (Criteria) this;
        }

        public Criteria andDomainidLessThan(Integer value) {
            addCriterion("domainid <", value, "domainid");
            return (Criteria) this;
        }

        public Criteria andDomainidLessThanOrEqualTo(Integer value) {
            addCriterion("domainid <=", value, "domainid");
            return (Criteria) this;
        }

        public Criteria andDomainidIn(List<Integer> values) {
            addCriterion("domainid in", values, "domainid");
            return (Criteria) this;
        }

        public Criteria andDomainidNotIn(List<Integer> values) {
            addCriterion("domainid not in", values, "domainid");
            return (Criteria) this;
        }

        public Criteria andDomainidBetween(Integer value1, Integer value2) {
            addCriterion("domainid between", value1, value2, "domainid");
            return (Criteria) this;
        }

        public Criteria andDomainidNotBetween(Integer value1, Integer value2) {
            addCriterion("domainid not between", value1, value2, "domainid");
            return (Criteria) this;
        }

        public Criteria andPosidIsNull() {
            addCriterion("posid is null");
            return (Criteria) this;
        }

        public Criteria andPosidIsNotNull() {
            addCriterion("posid is not null");
            return (Criteria) this;
        }

        public Criteria andPosidEqualTo(String value) {
            addCriterion("posid =", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidNotEqualTo(String value) {
            addCriterion("posid <>", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidGreaterThan(String value) {
            addCriterion("posid >", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidGreaterThanOrEqualTo(String value) {
            addCriterion("posid >=", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidLessThan(String value) {
            addCriterion("posid <", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidLessThanOrEqualTo(String value) {
            addCriterion("posid <=", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidLike(String value) {
            addCriterion("posid like", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidNotLike(String value) {
            addCriterion("posid not like", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidIn(List<String> values) {
            addCriterion("posid in", values, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidNotIn(List<String> values) {
            addCriterion("posid not in", values, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidBetween(String value1, String value2) {
            addCriterion("posid between", value1, value2, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidNotBetween(String value1, String value2) {
            addCriterion("posid not between", value1, value2, "posid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSizesIsNull() {
            addCriterion("sizes is null");
            return (Criteria) this;
        }

        public Criteria andSizesIsNotNull() {
            addCriterion("sizes is not null");
            return (Criteria) this;
        }

        public Criteria andSizesEqualTo(String value) {
            addCriterion("sizes =", value, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesNotEqualTo(String value) {
            addCriterion("sizes <>", value, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesGreaterThan(String value) {
            addCriterion("sizes >", value, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesGreaterThanOrEqualTo(String value) {
            addCriterion("sizes >=", value, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesLessThan(String value) {
            addCriterion("sizes <", value, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesLessThanOrEqualTo(String value) {
            addCriterion("sizes <=", value, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesLike(String value) {
            addCriterion("sizes like", value, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesNotLike(String value) {
            addCriterion("sizes not like", value, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesIn(List<String> values) {
            addCriterion("sizes in", values, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesNotIn(List<String> values) {
            addCriterion("sizes not in", values, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesBetween(String value1, String value2) {
            addCriterion("sizes between", value1, value2, "sizes");
            return (Criteria) this;
        }

        public Criteria andSizesNotBetween(String value1, String value2) {
            addCriterion("sizes not between", value1, value2, "sizes");
            return (Criteria) this;
        }

        public Criteria andPlaysizeIsNull() {
            addCriterion("playsize is null");
            return (Criteria) this;
        }

        public Criteria andPlaysizeIsNotNull() {
            addCriterion("playsize is not null");
            return (Criteria) this;
        }

        public Criteria andPlaysizeEqualTo(Integer value) {
            addCriterion("playsize =", value, "playsize");
            return (Criteria) this;
        }

        public Criteria andPlaysizeNotEqualTo(Integer value) {
            addCriterion("playsize <>", value, "playsize");
            return (Criteria) this;
        }

        public Criteria andPlaysizeGreaterThan(Integer value) {
            addCriterion("playsize >", value, "playsize");
            return (Criteria) this;
        }

        public Criteria andPlaysizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("playsize >=", value, "playsize");
            return (Criteria) this;
        }

        public Criteria andPlaysizeLessThan(Integer value) {
            addCriterion("playsize <", value, "playsize");
            return (Criteria) this;
        }

        public Criteria andPlaysizeLessThanOrEqualTo(Integer value) {
            addCriterion("playsize <=", value, "playsize");
            return (Criteria) this;
        }

        public Criteria andPlaysizeIn(List<Integer> values) {
            addCriterion("playsize in", values, "playsize");
            return (Criteria) this;
        }

        public Criteria andPlaysizeNotIn(List<Integer> values) {
            addCriterion("playsize not in", values, "playsize");
            return (Criteria) this;
        }

        public Criteria andPlaysizeBetween(Integer value1, Integer value2) {
            addCriterion("playsize between", value1, value2, "playsize");
            return (Criteria) this;
        }

        public Criteria andPlaysizeNotBetween(Integer value1, Integer value2) {
            addCriterion("playsize not between", value1, value2, "playsize");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayIsNull() {
            addCriterion("pretimesperday is null");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayIsNotNull() {
            addCriterion("pretimesperday is not null");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayEqualTo(Integer value) {
            addCriterion("pretimesperday =", value, "pretimesperday");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayNotEqualTo(Integer value) {
            addCriterion("pretimesperday <>", value, "pretimesperday");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayGreaterThan(Integer value) {
            addCriterion("pretimesperday >", value, "pretimesperday");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayGreaterThanOrEqualTo(Integer value) {
            addCriterion("pretimesperday >=", value, "pretimesperday");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayLessThan(Integer value) {
            addCriterion("pretimesperday <", value, "pretimesperday");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayLessThanOrEqualTo(Integer value) {
            addCriterion("pretimesperday <=", value, "pretimesperday");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayIn(List<Integer> values) {
            addCriterion("pretimesperday in", values, "pretimesperday");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayNotIn(List<Integer> values) {
            addCriterion("pretimesperday not in", values, "pretimesperday");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayBetween(Integer value1, Integer value2) {
            addCriterion("pretimesperday between", value1, value2, "pretimesperday");
            return (Criteria) this;
        }

        public Criteria andPretimesperdayNotBetween(Integer value1, Integer value2) {
            addCriterion("pretimesperday not between", value1, value2, "pretimesperday");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodIsNull() {
            addCriterion("refreshperiod is null");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodIsNotNull() {
            addCriterion("refreshperiod is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodEqualTo(Integer value) {
            addCriterion("refreshperiod =", value, "refreshperiod");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodNotEqualTo(Integer value) {
            addCriterion("refreshperiod <>", value, "refreshperiod");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodGreaterThan(Integer value) {
            addCriterion("refreshperiod >", value, "refreshperiod");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodGreaterThanOrEqualTo(Integer value) {
            addCriterion("refreshperiod >=", value, "refreshperiod");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodLessThan(Integer value) {
            addCriterion("refreshperiod <", value, "refreshperiod");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodLessThanOrEqualTo(Integer value) {
            addCriterion("refreshperiod <=", value, "refreshperiod");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodIn(List<Integer> values) {
            addCriterion("refreshperiod in", values, "refreshperiod");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodNotIn(List<Integer> values) {
            addCriterion("refreshperiod not in", values, "refreshperiod");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodBetween(Integer value1, Integer value2) {
            addCriterion("refreshperiod between", value1, value2, "refreshperiod");
            return (Criteria) this;
        }

        public Criteria andRefreshperiodNotBetween(Integer value1, Integer value2) {
            addCriterion("refreshperiod not between", value1, value2, "refreshperiod");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Integer value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Integer value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Integer value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Integer value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Integer value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Integer> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Integer> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Integer value1, Integer value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andUsableflagIsNull() {
            addCriterion("usableflag is null");
            return (Criteria) this;
        }

        public Criteria andUsableflagIsNotNull() {
            addCriterion("usableflag is not null");
            return (Criteria) this;
        }

        public Criteria andUsableflagEqualTo(String value) {
            addCriterion("usableflag =", value, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagNotEqualTo(String value) {
            addCriterion("usableflag <>", value, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagGreaterThan(String value) {
            addCriterion("usableflag >", value, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagGreaterThanOrEqualTo(String value) {
            addCriterion("usableflag >=", value, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagLessThan(String value) {
            addCriterion("usableflag <", value, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagLessThanOrEqualTo(String value) {
            addCriterion("usableflag <=", value, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagLike(String value) {
            addCriterion("usableflag like", value, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagNotLike(String value) {
            addCriterion("usableflag not like", value, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagIn(List<String> values) {
            addCriterion("usableflag in", values, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagNotIn(List<String> values) {
            addCriterion("usableflag not in", values, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagBetween(String value1, String value2) {
            addCriterion("usableflag between", value1, value2, "usableflag");
            return (Criteria) this;
        }

        public Criteria andUsableflagNotBetween(String value1, String value2) {
            addCriterion("usableflag not between", value1, value2, "usableflag");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andStaffidIsNull() {
            addCriterion("staffid is null");
            return (Criteria) this;
        }

        public Criteria andStaffidIsNotNull() {
            addCriterion("staffid is not null");
            return (Criteria) this;
        }

        public Criteria andStaffidEqualTo(Integer value) {
            addCriterion("staffid =", value, "staffid");
            return (Criteria) this;
        }

        public Criteria andStaffidNotEqualTo(Integer value) {
            addCriterion("staffid <>", value, "staffid");
            return (Criteria) this;
        }

        public Criteria andStaffidGreaterThan(Integer value) {
            addCriterion("staffid >", value, "staffid");
            return (Criteria) this;
        }

        public Criteria andStaffidGreaterThanOrEqualTo(Integer value) {
            addCriterion("staffid >=", value, "staffid");
            return (Criteria) this;
        }

        public Criteria andStaffidLessThan(Integer value) {
            addCriterion("staffid <", value, "staffid");
            return (Criteria) this;
        }

        public Criteria andStaffidLessThanOrEqualTo(Integer value) {
            addCriterion("staffid <=", value, "staffid");
            return (Criteria) this;
        }

        public Criteria andStaffidIn(List<Integer> values) {
            addCriterion("staffid in", values, "staffid");
            return (Criteria) this;
        }

        public Criteria andStaffidNotIn(List<Integer> values) {
            addCriterion("staffid not in", values, "staffid");
            return (Criteria) this;
        }

        public Criteria andStaffidBetween(Integer value1, Integer value2) {
            addCriterion("staffid between", value1, value2, "staffid");
            return (Criteria) this;
        }

        public Criteria andStaffidNotBetween(Integer value1, Integer value2) {
            addCriterion("staffid not between", value1, value2, "staffid");
            return (Criteria) this;
        }

        public Criteria andDefaultadidIsNull() {
            addCriterion("defaultadid is null");
            return (Criteria) this;
        }

        public Criteria andDefaultadidIsNotNull() {
            addCriterion("defaultadid is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultadidEqualTo(Integer value) {
            addCriterion("defaultadid =", value, "defaultadid");
            return (Criteria) this;
        }

        public Criteria andDefaultadidNotEqualTo(Integer value) {
            addCriterion("defaultadid <>", value, "defaultadid");
            return (Criteria) this;
        }

        public Criteria andDefaultadidGreaterThan(Integer value) {
            addCriterion("defaultadid >", value, "defaultadid");
            return (Criteria) this;
        }

        public Criteria andDefaultadidGreaterThanOrEqualTo(Integer value) {
            addCriterion("defaultadid >=", value, "defaultadid");
            return (Criteria) this;
        }

        public Criteria andDefaultadidLessThan(Integer value) {
            addCriterion("defaultadid <", value, "defaultadid");
            return (Criteria) this;
        }

        public Criteria andDefaultadidLessThanOrEqualTo(Integer value) {
            addCriterion("defaultadid <=", value, "defaultadid");
            return (Criteria) this;
        }

        public Criteria andDefaultadidIn(List<Integer> values) {
            addCriterion("defaultadid in", values, "defaultadid");
            return (Criteria) this;
        }

        public Criteria andDefaultadidNotIn(List<Integer> values) {
            addCriterion("defaultadid not in", values, "defaultadid");
            return (Criteria) this;
        }

        public Criteria andDefaultadidBetween(Integer value1, Integer value2) {
            addCriterion("defaultadid between", value1, value2, "defaultadid");
            return (Criteria) this;
        }

        public Criteria andDefaultadidNotBetween(Integer value1, Integer value2) {
            addCriterion("defaultadid not between", value1, value2, "defaultadid");
            return (Criteria) this;
        }

        public Criteria andDurationIsNull() {
            addCriterion("duration is null");
            return (Criteria) this;
        }

        public Criteria andDurationIsNotNull() {
            addCriterion("duration is not null");
            return (Criteria) this;
        }

        public Criteria andDurationEqualTo(Integer value) {
            addCriterion("duration =", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotEqualTo(Integer value) {
            addCriterion("duration <>", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThan(Integer value) {
            addCriterion("duration >", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("duration >=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThan(Integer value) {
            addCriterion("duration <", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationLessThanOrEqualTo(Integer value) {
            addCriterion("duration <=", value, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationIn(List<Integer> values) {
            addCriterion("duration in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotIn(List<Integer> values) {
            addCriterion("duration not in", values, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationBetween(Integer value1, Integer value2) {
            addCriterion("duration between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("duration not between", value1, value2, "duration");
            return (Criteria) this;
        }

        public Criteria andTopIsNull() {
            addCriterion("top is null");
            return (Criteria) this;
        }

        public Criteria andTopIsNotNull() {
            addCriterion("top is not null");
            return (Criteria) this;
        }

        public Criteria andTopEqualTo(String value) {
            addCriterion("top =", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopNotEqualTo(String value) {
            addCriterion("top <>", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopGreaterThan(String value) {
            addCriterion("top >", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopGreaterThanOrEqualTo(String value) {
            addCriterion("top >=", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopLessThan(String value) {
            addCriterion("top <", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopLessThanOrEqualTo(String value) {
            addCriterion("top <=", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopLike(String value) {
            addCriterion("top like", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopNotLike(String value) {
            addCriterion("top not like", value, "top");
            return (Criteria) this;
        }

        public Criteria andTopIn(List<String> values) {
            addCriterion("top in", values, "top");
            return (Criteria) this;
        }

        public Criteria andTopNotIn(List<String> values) {
            addCriterion("top not in", values, "top");
            return (Criteria) this;
        }

        public Criteria andTopBetween(String value1, String value2) {
            addCriterion("top between", value1, value2, "top");
            return (Criteria) this;
        }

        public Criteria andTopNotBetween(String value1, String value2) {
            addCriterion("top not between", value1, value2, "top");
            return (Criteria) this;
        }

        public Criteria andLeftIsNull() {
            addCriterion("left is null");
            return (Criteria) this;
        }

        public Criteria andLeftIsNotNull() {
            addCriterion("left is not null");
            return (Criteria) this;
        }

        public Criteria andLeftEqualTo(String value) {
            addCriterion("left =", value, "left");
            return (Criteria) this;
        }

        public Criteria andLeftNotEqualTo(String value) {
            addCriterion("left <>", value, "left");
            return (Criteria) this;
        }

        public Criteria andLeftGreaterThan(String value) {
            addCriterion("left >", value, "left");
            return (Criteria) this;
        }

        public Criteria andLeftGreaterThanOrEqualTo(String value) {
            addCriterion("left >=", value, "left");
            return (Criteria) this;
        }

        public Criteria andLeftLessThan(String value) {
            addCriterion("left <", value, "left");
            return (Criteria) this;
        }

        public Criteria andLeftLessThanOrEqualTo(String value) {
            addCriterion("left <=", value, "left");
            return (Criteria) this;
        }

        public Criteria andLeftLike(String value) {
            addCriterion("left like", value, "left");
            return (Criteria) this;
        }

        public Criteria andLeftNotLike(String value) {
            addCriterion("left not like", value, "left");
            return (Criteria) this;
        }

        public Criteria andLeftIn(List<String> values) {
            addCriterion("left in", values, "left");
            return (Criteria) this;
        }

        public Criteria andLeftNotIn(List<String> values) {
            addCriterion("left not in", values, "left");
            return (Criteria) this;
        }

        public Criteria andLeftBetween(String value1, String value2) {
            addCriterion("left between", value1, value2, "left");
            return (Criteria) this;
        }

        public Criteria andLeftNotBetween(String value1, String value2) {
            addCriterion("left not between", value1, value2, "left");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(String value) {
            addCriterion("width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(String value) {
            addCriterion("width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(String value) {
            addCriterion("width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(String value) {
            addCriterion("width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(String value) {
            addCriterion("width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(String value) {
            addCriterion("width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLike(String value) {
            addCriterion("width like", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotLike(String value) {
            addCriterion("width not like", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<String> values) {
            addCriterion("width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<String> values) {
            addCriterion("width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(String value1, String value2) {
            addCriterion("width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(String value1, String value2) {
            addCriterion("width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(String value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(String value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(String value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(String value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(String value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(String value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLike(String value) {
            addCriterion("height like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotLike(String value) {
            addCriterion("height not like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<String> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<String> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(String value1, String value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(String value1, String value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andShowtypeIsNull() {
            addCriterion("showtype is null");
            return (Criteria) this;
        }

        public Criteria andShowtypeIsNotNull() {
            addCriterion("showtype is not null");
            return (Criteria) this;
        }

        public Criteria andShowtypeEqualTo(String value) {
            addCriterion("showtype =", value, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeNotEqualTo(String value) {
            addCriterion("showtype <>", value, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeGreaterThan(String value) {
            addCriterion("showtype >", value, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeGreaterThanOrEqualTo(String value) {
            addCriterion("showtype >=", value, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeLessThan(String value) {
            addCriterion("showtype <", value, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeLessThanOrEqualTo(String value) {
            addCriterion("showtype <=", value, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeLike(String value) {
            addCriterion("showtype like", value, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeNotLike(String value) {
            addCriterion("showtype not like", value, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeIn(List<String> values) {
            addCriterion("showtype in", values, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeNotIn(List<String> values) {
            addCriterion("showtype not in", values, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeBetween(String value1, String value2) {
            addCriterion("showtype between", value1, value2, "showtype");
            return (Criteria) this;
        }

        public Criteria andShowtypeNotBetween(String value1, String value2) {
            addCriterion("showtype not between", value1, value2, "showtype");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeIsNull() {
            addCriterion("epgtempalatecode is null");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeIsNotNull() {
            addCriterion("epgtempalatecode is not null");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeEqualTo(String value) {
            addCriterion("epgtempalatecode =", value, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeNotEqualTo(String value) {
            addCriterion("epgtempalatecode <>", value, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeGreaterThan(String value) {
            addCriterion("epgtempalatecode >", value, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeGreaterThanOrEqualTo(String value) {
            addCriterion("epgtempalatecode >=", value, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeLessThan(String value) {
            addCriterion("epgtempalatecode <", value, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeLessThanOrEqualTo(String value) {
            addCriterion("epgtempalatecode <=", value, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeLike(String value) {
            addCriterion("epgtempalatecode like", value, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeNotLike(String value) {
            addCriterion("epgtempalatecode not like", value, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeIn(List<String> values) {
            addCriterion("epgtempalatecode in", values, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeNotIn(List<String> values) {
            addCriterion("epgtempalatecode not in", values, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeBetween(String value1, String value2) {
            addCriterion("epgtempalatecode between", value1, value2, "epgtempalatecode");
            return (Criteria) this;
        }

        public Criteria andEpgtempalatecodeNotBetween(String value1, String value2) {
            addCriterion("epgtempalatecode not between", value1, value2, "epgtempalatecode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adplace
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table adplace
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}