package com.utstar.adhandler.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table staff
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Staff implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.STAFFID
     *
     * @mbg.generated
     */
    private Integer staffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.CREATEDATE
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.CREATEUSER
     *
     * @mbg.generated
     */
    private Integer createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.DESCRIPTION
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.LASTUPDATE
     *
     * @mbg.generated
     */
    private Date lastupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.LOGINFLAG
     *
     * @mbg.generated
     */
    private String loginflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.DELETEFLAG
     *
     * @mbg.generated
     */
    private String deleteflag;

    /**
     * Database Column Remarks:
     *   用户类型,0:default,非模板用户; 1:集团模板用户; 2:省份模板用户; 3:广告主/广告代理商模板用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table staff
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.STAFFID
     *
     * @return the value of staff.STAFFID
     *
     * @mbg.generated
     */
    public Integer getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.STAFFID
     *
     * @param staffid the value for staff.STAFFID
     *
     * @mbg.generated
     */
    public void setStaffid(Integer staffid) {
        this.staffid = staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.CREATEDATE
     *
     * @return the value of staff.CREATEDATE
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.CREATEDATE
     *
     * @param createdate the value for staff.CREATEDATE
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.CREATEUSER
     *
     * @return the value of staff.CREATEUSER
     *
     * @mbg.generated
     */
    public Integer getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.CREATEUSER
     *
     * @param createuser the value for staff.CREATEUSER
     *
     * @mbg.generated
     */
    public void setCreateuser(Integer createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.DESCRIPTION
     *
     * @return the value of staff.DESCRIPTION
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.DESCRIPTION
     *
     * @param description the value for staff.DESCRIPTION
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.LASTUPDATE
     *
     * @return the value of staff.LASTUPDATE
     *
     * @mbg.generated
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.LASTUPDATE
     *
     * @param lastupdate the value for staff.LASTUPDATE
     *
     * @mbg.generated
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.LOGINFLAG
     *
     * @return the value of staff.LOGINFLAG
     *
     * @mbg.generated
     */
    public String getLoginflag() {
        return loginflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.LOGINFLAG
     *
     * @param loginflag the value for staff.LOGINFLAG
     *
     * @mbg.generated
     */
    public void setLoginflag(String loginflag) {
        this.loginflag = loginflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.NAME
     *
     * @return the value of staff.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.NAME
     *
     * @param name the value for staff.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.PASSWORD
     *
     * @return the value of staff.PASSWORD
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.PASSWORD
     *
     * @param password the value for staff.PASSWORD
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.STATUS
     *
     * @return the value of staff.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.STATUS
     *
     * @param status the value for staff.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.DELETEFLAG
     *
     * @return the value of staff.DELETEFLAG
     *
     * @mbg.generated
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.DELETEFLAG
     *
     * @param deleteflag the value for staff.DELETEFLAG
     *
     * @mbg.generated
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.type
     *
     * @return the value of staff.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.type
     *
     * @param type the value for staff.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }
}