package com.utstar.adhandler.mapper;

import com.utstar.adhandler.entity.Globalcodedef;
import com.utstar.adhandler.entity.GlobalcodedefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GlobalcodedefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    long countByExample(GlobalcodedefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    int deleteByExample(GlobalcodedefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer globalcodedefid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    int insert(Globalcodedef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    int insertSelective(Globalcodedef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    List<Globalcodedef> selectByExample(GlobalcodedefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    Globalcodedef selectByPrimaryKey(Integer globalcodedefid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Globalcodedef record, @Param("example") GlobalcodedefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Globalcodedef record, @Param("example") GlobalcodedefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Globalcodedef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table globalcodedef
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Globalcodedef record);
}