package com.utstar.adhandler.vo;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class AdplaceReq implements Serializable {

    private Integer domainid;
    private String posid;
    private String name;
    private String code;
    private String type;

    /**
     * Database Column Remarks:
     * 尺寸,格式如400*300,单位px
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.sizes
     *
     * @mbg.generated
     */
    private String sizes;

    private Integer playsize;

    /**
     * Database Column Remarks:
     * 预估平均日流量，单位：次
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.pretimesperday
     *
     * @mbg.generated
     */
    private Integer pretimesperday;

    /**
     * Database Column Remarks:
     * 刷新周期，单位：分钟
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.refreshperiod
     *
     * @mbg.generated
     */
    private Integer refreshperiod;

    /**
     * Database Column Remarks:
     * 广告位价格，单位：元
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.price
     *
     * @mbg.generated
     */
    private Integer price;

    /**
     * Database Column Remarks:
     * 默认广告id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.defaultadid
     *
     * @mbg.generated
     */
    private Integer defaultadid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     * Database Column Remarks:
     * 左上坐标
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.top
     *
     * @mbg.generated
     */
    private String top;

    /**
     * Database Column Remarks:
     * 左下坐标
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.left
     *
     * @mbg.generated
     */
    private String left;

    /**
     * Database Column Remarks:
     * 宽度
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.width
     *
     * @mbg.generated
     */
    private String width;

    /**
     * Database Column Remarks:
     * 高度
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.height
     *
     * @mbg.generated
     */
    private String height;

    /**
     * Database Column Remarks:
     * 广告显示方式
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.showtype
     *
     * @mbg.generated
     */
    private String showtype;

    /**
     * Database Column Remarks:
     * EPG模板代码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adplace.epgtempalatecode
     *
     * @mbg.generated
     */
    private String epgtempalatecode;

    private static final long serialVersionUID = 1L;

}